trigger:
    branches:
        include:
            - main

pool:
  name: 'MyAgentPool'
  vmImage: 'ubuntu-latest'

stages:
    - stage: Build
      jobs:
        - job: Build
          steps:
            - script: echo "Building the application"
              displayName: "Build"
            - task: Docker@2
              displayName: Build an image
              inputs:
                repository: "https://github.com/Dishaangsali/Spring-Boot-Sample-Project.git"
                command: Build
                Dockerfile: Dockerfile

    - stage: Test
      jobs:
        - job: Test
          steps:
            - script: echo "Running tests for application"
              displayName: "Test"

    - stage: Deploy
      jobs:
        - job: Deploy
          steps:
            - script: echo "Deploying application to production"
              displayName: "Deploy"