trigger:
    branches:
        include:
            - main

stages:
    - stage: Build
      jobs:
        - job: Build
          pool:
            -name: 'MyAgentPool'
          steps:
            - script: echo "Building the application"
              displayName: "Build"

    - stage: Test
      jobs:
        - job: Test
          pool:
            -name: 'MyAgentPool'
          steps:
            - script: echo "Running tests for application"
              displayName: "Test"

    - stage: Deploy
      jobs:
        - job: Deploy
          pool:
            -name: 'MyAgentPool'
          steps:
            - script: echo "Deploying application to production"
              displayName: "Deploy"
