trigger:
    branches:
        include:
            -main

stages:
    -stage: Build
     jobs:
        -job: Build
         steps:
            -script: echo "Building the application"
             displayName: "Build"

    -stage: Test
     jobs:
        -job: Test
         steps:
            -script: echo "Running tests for application"
             displayName: "Test"

    -stage: Deploy
     jobs:
        -job: Deploy
         steps:
            -script: echo "Deploying application to production"
             displayName: "Deploy"
